import React, { useEffect, useMemo, useState } from 'react'
import { createRoot } from 'react-dom/client'
import ReactMarkdown from 'react-markdown'
import { BookOpen, CheckCircle2, ChevronRight, CirclePlay, Code2, Flame, Home, LogOut, Menu, Play, Settings, Sparkles, Terminal, Trophy, X } from 'lucide-react'
import './styles.css'

const API = import.meta.env.VITE_API_URL || '/api'
type Lesson = { id:number; title:string; order:number; duration:number; markdown:string; exercises:{id:number; prompt:string; starter_code:string}[] }
type Course = { id:number; title:string; slug:string; description:string; level:string; accent:string; lessons:Lesson[] }
type User = { id:number; name:string; email:string }

async function request<T>(path:string, options:RequestInit = {}):Promise<T> {
  const token = localStorage.getItem('pytrail_token')
  const response = await fetch(`${API}${path}`, { ...options, headers: { 'Content-Type':'application/json', ...(token ? { Authorization:`Bearer ${token}` } : {}), ...(options.headers || {}) } })
  if (!response.ok) throw new Error((await response.json()).detail || 'Request failed')
  return response.json()
}

function App() {
  const [user, setUser] = useState<User | null>(null)
  const [courses, setCourses] = useState<Course[]>([])
  const [dashboard, setDashboard] = useState({ lessons_total: 4, lessons_completed: 0, completion: 0, average_score: 0, streak: 4 })
  const [selectedLesson, setSelectedLesson] = useState<Lesson | null>(null)
  const [tab, setTab] = useState<'overview'|'course'|'practice'>('overview')
  const [authOpen, setAuthOpen] = useState(false)
  const [mobileNav, setMobileNav] = useState(false)
  useEffect(() => { request<Course[]>('/courses').then(setCourses).catch(() => {}) ; if (localStorage.getItem('pytrail_token')) { request<User>('/auth/me').then(u => { setUser(u); request<typeof dashboard>('/dashboard').then(setDashboard).catch(() => {}) }).catch(() => localStorage.removeItem('pytrail_token')) } }, [])
  const course = courses[0]
  const recent = useMemo(() => course?.lessons.slice(0, 3) || [], [course])
  const openLesson = (lesson:Lesson | undefined) => { if (!lesson) return; setSelectedLesson(lesson); setTab('course'); setMobileNav(false) }
  const signOut = () => { localStorage.removeItem('pytrail_token'); setUser(null) }
  return <div className="app-shell">
    <aside className={`sidebar ${mobileNav ? 'open' : ''}`}>
      <div className="brand"><span className="brand-mark">py</span><span>PyTrail</span></div>
      <div className="workspace-label">YOUR WORKSPACE</div>
      <nav>
        <button className={tab === 'overview' ? 'nav-item active' : 'nav-item'} onClick={() => {setTab('overview');setSelectedLesson(null);setMobileNav(false)}}><Home size={18}/> Overview</button>
        <button className={tab === 'course' ? 'nav-item active' : 'nav-item'} onClick={() => {setTab('course');setMobileNav(false)}}><BookOpen size={18}/> My courses <span className="nav-count">1</span></button>
        <button className={tab === 'practice' ? 'nav-item active' : 'nav-item'} onClick={() => {setTab('practice');setMobileNav(false)}}><Code2 size={18}/> Practice lab <span className="new-pill">NEW</span></button>
      </nav>
      <div className="sidebar-bottom"><button className="nav-item"><Settings size={18}/> Settings</button>{user ? <button className="nav-item" onClick={signOut}><LogOut size={18}/> Sign out</button> : <button className="nav-item" onClick={() => setAuthOpen(true)}><Sparkles size={18}/> Sign in</button>}</div>
    </aside>
    {mobileNav && <button className="scrim" aria-label="Close navigation" onClick={() => setMobileNav(false)} />}
    <main className="main-content">
      <header className="topbar"><button className="icon-btn mobile-menu" onClick={() => setMobileNav(true)}><Menu size={20}/></button><div className="breadcrumb"><span>Workspace</span><ChevronRight size={14}/><strong>{tab === 'overview' ? 'Overview' : tab === 'course' ? 'Python Foundations' : 'Practice lab'}</strong></div><div className="top-actions"><span className="streak"><Flame size={17} fill="currentColor"/> {dashboard.streak} day streak</span>{user ? <div className="avatar" title={user.email}>{user.name.slice(0,1).toUpperCase()}</div> : <button className="text-btn" onClick={() => setAuthOpen(true)}>Log in</button>}</div></header>
      {tab === 'overview' && <Overview course={course} lessons={recent} dashboard={dashboard} openLesson={openLesson} onStart={() => openLesson(course?.lessons[0])} />}
      {tab === 'course' && <CourseView course={course} selectedLesson={selectedLesson} openLesson={openLesson} user={user} onAuth={() => setAuthOpen(true)} />}
      {tab === 'practice' && <PracticeView course={course} openLesson={openLesson} />}
    </main>
    {authOpen && <AuthModal onClose={() => setAuthOpen(false)} onAuth={(u, token) => {localStorage.setItem('pytrail_token', token);setUser(u);setAuthOpen(false);request<typeof dashboard>('/dashboard').then(setDashboard).catch(()=>{})}} />}
  </div>
}

function Overview({course, lessons, dashboard, openLesson, onStart}:{course?:Course;lessons:Lesson[];dashboard:{lessons_total:number;lessons_completed:number;completion:number;average_score:number;streak:number};openLesson:(l:Lesson)=>void;onStart:()=>void}) {
  return <div className="page"><section className="welcome-row"><div><p className="eyebrow">THURSDAY, AUGUST 13</p><h1>Good morning<span className="accent-dot">.</span></h1><p className="muted">Small steps compound. Keep your Python journey moving.</p></div><button className="primary-btn" onClick={onStart}><CirclePlay size={18} fill="currentColor"/> Continue learning</button></section>
    <section className="stats-grid"><Stat label="Course progress" value={`${dashboard.completion}%`} detail={`${dashboard.lessons_completed} of ${dashboard.lessons_total} lessons`} icon={<BookOpen/>} tone="cyan"/><Stat label="Average score" value={`${dashboard.average_score || 0}%`} detail="Across all exercises" icon={<Trophy/>} tone="violet"/><Stat label="Learning streak" value={`${dashboard.streak} days`} detail="Best: 12 days" icon={<Flame/>} tone="orange"/></section>
    <section className="section-heading"><div><p className="eyebrow">YOUR PATH</p><h2>Pick up where you left off</h2></div><button className="link-btn">View course <ChevronRight size={16}/></button></section>
    {course && <article className="course-feature"><div className="course-copy"><div className="course-badge">PYTHON 101 <span>•</span> {course.level.toUpperCase()}</div><h3>{course.title}</h3><p>{course.description}</p><div className="progress-line"><span style={{width:`${Math.max(dashboard.completion, 8)}%`}}/></div><div className="course-meta"><span>{dashboard.lessons_completed}/{course.lessons.length} lessons</span><span>{course.lessons.reduce((a,l)=>a+l.duration,0)} min total</span></div></div><div className="course-visual"><div className="code-window"><div className="window-bar"><i/><i/><i/></div><pre><span className="pink">def</span> <span className="yellow">hello</span>(name):{`\n`}    <span className="pink">return</span> <span className="green">f</span><span className="green">\"Welcome, {`{`}name{`}`}!\"</span></pre><span className="play-float"><Play size={15} fill="currentColor"/></span></div></div></article>}
    <section className="section-heading compact"><div><p className="eyebrow">UP NEXT</p><h2>Recent lessons</h2></div></section><div className="lesson-list">{lessons.map((lesson, i) => <button className="lesson-row" key={lesson.id} onClick={() => openLesson(lesson)}><span className={`lesson-index ${i === 0 ? 'current' : ''}`}>{i === 0 ? <Play size={13} fill="currentColor"/> : lesson.order}</span><span className="lesson-title"><strong>{lesson.title}</strong><small>Python Foundations</small></span><span className="lesson-duration">{lesson.duration} min</span><ChevronRight size={17}/></button>)}</div>
  </div>
}
function Stat({label,value,detail,icon,tone}:{label:string;value:string;detail:string;icon:React.ReactNode;tone:string}) { return <div className="stat-card"><div className={`stat-icon ${tone}`}>{icon}</div><div><p>{label}</p><strong>{value}</strong><small>{detail}</small></div></div> }

function CourseView({course,selectedLesson,openLesson,user,onAuth}:{course?:Course;selectedLesson:Lesson|null;openLesson:(l:Lesson)=>void;user:User|null;onAuth:()=>void}) { const lesson = selectedLesson || course?.lessons[0]; return <div className="page course-page"><div className="course-header"><div><p className="eyebrow">COURSE / PYTHON 101</p><h1>{course?.title || 'Python Foundations'}</h1><p className="muted">{course?.description}</p></div><div className="course-progress-chip"><strong>0%</strong><span>complete</span></div></div><div className="course-layout"><aside className="lesson-sidebar"><p className="eyebrow">LESSONS</p>{course?.lessons.map((item, idx) => <button key={item.id} className={`lesson-nav ${lesson?.id===item.id?'selected':''}`} onClick={() => openLesson(item)}><span>{idx+1}</span><span>{item.title}<small>{item.duration} min</small></span>{idx===0 && <CheckCircle2 size={16}/>}</button>)}</aside><article className="lesson-content">{lesson ? <><div className="lesson-kicker">LESSON {lesson.order} <span>•</span> {lesson.duration} MIN</div><h2>{lesson.title}</h2><div className="markdown"><ReactMarkdown>{lesson.markdown}</ReactMarkdown></div><CodeRunner initial={lesson.exercises[0]?.starter_code || 'print("Hello, Python!")'} user={user} onAuth={onAuth}/>{lesson.exercises[0] && <ExerciseCard exercise={lesson.exercises[0]} user={user} onAuth={onAuth}/>} {!user && <div className="signin-note"><Sparkles size={17}/><span>Sign in to save your progress and keep your streak alive.</span><button className="link-btn" onClick={onAuth}>Create free account</button></div>}</> : <EmptyState/>}</article></div></div> }

function CodeRunner({initial,user,onAuth}:{initial:string;user:User|null;onAuth:()=>void}) { const [code,setCode]=useState(initial); const [output,setOutput]=useState('Run your code to see output here.'); const [running,setRunning]=useState(false); const run = async () => { setRunning(true); try { const result = await request<{stdout:string;stderr:string;ok:boolean}>('/execute',{method:'POST',body:JSON.stringify({code})}); setOutput(result.stdout || result.stderr || 'No output'); } catch { setOutput('Connect the API to run Python code.'); } finally { setRunning(false) } }; return <div className="code-runner"><div className="runner-head"><div><Terminal size={16}/> Playground</div><span>Python 3.12</span></div><textarea value={code} onChange={e=>setCode(e.target.value)} spellCheck={false}/><div className="runner-foot"><button className="run-btn" onClick={run} disabled={running}><Play size={14} fill="currentColor"/> {running?'Running...':'Run code'}</button><code>⌘ + Enter</code><pre>{output}</pre></div></div> }
function ExerciseCard({exercise,user,onAuth}:{exercise:{id:number;prompt:string};user:User|null;onAuth:()=>void}) { const [answer,setAnswer]=useState(''); const [result,setResult]=useState<{correct:boolean;message:string}|null>(null); const submit = async () => { if (!user) return onAuth(); try { setResult(await request<{correct:boolean;message:string}>(`/exercises/${exercise.id}/submit`,{method:'POST',body:JSON.stringify({answer})})) } catch {} }; return <div className="exercise-card"><div className="exercise-label"><Code2 size={16}/> QUICK CHECK</div><h3>{exercise.prompt}</h3><div className="answer-row"><input value={answer} onChange={e=>setAnswer(e.target.value)} placeholder="Type your answer..."/><button className="secondary-btn" onClick={submit}>Check answer</button></div>{result && <p className={result.correct?'success':'error'}>{result.message}</p>}</div> }
function PracticeView({course,openLesson}:{course?:Course;openLesson:(l:Lesson)=>void}) { return <div className="page practice-page"><div className="welcome-row"><div><p className="eyebrow">PRACTICE LAB</p><h1>Learn by doing<span className="accent-dot">.</span></h1><p className="muted">Short challenges to make Python stick.</p></div></div><div className="practice-grid">{course?.lessons.map((lesson, i)=><button className="practice-card" key={lesson.id} onClick={()=>openLesson(lesson)}><div className="practice-number">0{i+1}</div><div><h3>{lesson.title}</h3><p>{lesson.exercises[0]?.prompt || 'Explore this concept in the playground.'}</p><span>Open challenge <ChevronRight size={15}/></span></div></button>)}</div></div> }
function EmptyState(){ return <div className="empty"><BookOpen size={28}/><h2>Select a lesson</h2><p>Choose a lesson from the left to begin.</p></div> }
function AuthModal({onClose,onAuth}:{onClose:()=>void;onAuth:(u:User,t:string)=>void}) { const [mode,setMode]=useState<'login'|'register'>('login'); const [name,setName]=useState(''); const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [error,setError]=useState(''); const submit=async(e:React.FormEvent)=>{e.preventDefault();setError('');try{const data=await request<{user:User;access_token:string}>(`/auth/${mode}`,{method:'POST',body:JSON.stringify(mode==='login'?{email,password}:{name,email,password})});onAuth(data.user,data.access_token)}catch(err){setError((err as Error).message)}}; return <div className="modal-backdrop"><div className="auth-modal"><button className="icon-btn close-btn" onClick={onClose}><X size={19}/></button><div className="brand modal-brand"><span className="brand-mark">py</span><span>PyTrail</span></div><h2>{mode==='login'?'Welcome back':'Start your journey'}</h2><p className="muted">{mode==='login'?'Continue where you left off.':'Create an account and track every win.'}</p><form onSubmit={submit}>{mode==='register'&&<input value={name} onChange={e=>setName(e.target.value)} placeholder="Your name" required/>}<input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="Email address" required/><input type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Password (8+ characters)" required minLength={8}/>{error&&<p className="error">{error}</p>}<button className="primary-btn full" type="submit">{mode==='login'?'Log in':'Create account'} <ChevronRight size={17}/></button></form><button className="switch-auth" onClick={()=>setMode(mode==='login'?'register':'login')}>{mode==='login'?"Don't have an account? Create one":"Already have an account? Log in"}</button></div></div> }

createRoot(document.getElementById('root')!).render(<App />)
